apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
  - ../../base/metallb/metallb-chart.yaml
  - ../../base/metallb/metallb-system-namespace.yaml
configMapGenerator:
  - name: metallb-values
    files:
      - values.yaml=values.yaml
configurations:
  - ../../base/metallb/kustomizeconfig.yaml
