apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: sources
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: kavm
  path: ./apps/local
  prune: true
  validation: client
