apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../base/ingress-nginx/ingress-nginx.yaml
configMapGenerator:
  - name: ingress-nginx-values
    files:
      - values.yaml=values.yaml
configurations:
  - ../../base/ingress-nginx/kustomizeconfig.yaml
